import { test, expect } from '@playwright/test'
import { readFile, unlink } from 'node:fs/promises'
import path from 'node:path'

test('real PDF extraction, engineering corrections, one-step confirmation and exports',async({page,request})=>{
  test.setTimeout(300000)
  let recordId=''
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  try{
    await page.goto('/')
    await page.getByRole('button',{name:'Capture a new form'}).click()
    await expect(page.getByRole('button',{name:'Process Form',exact:true})).toBeDisabled()
    await page.locator('input[type=file][multiple]').setInputFiles('public/reference-u1.pdf')
    await expect(page.locator('.u-page-tile')).toHaveCount(3)
    await page.getByRole('button',{name:'Move page 1 later'}).click()
    await expect(page.locator('.u-page-tile').first()).toContainText('page 2')
    await page.getByRole('button',{name:'Move page 1 later'}).click()
    await page.getByRole('button',{name:'Preview page 1',exact:true}).click()
    await page.getByRole('button',{name:'Detect edges',exact:true}).click()
    await page.getByRole('button',{name:'Reset crop',exact:true}).click()
    await page.getByRole('button',{name:'Close preview',exact:true}).click()
    await page.getByLabel('Record name',{exact:true}).fill('QA reference · real OCR')
    const creation=page.waitForResponse(r=>r.url().endsWith('/api/u1/records')&&r.request().method()==='POST')
    await page.getByRole('button',{name:'Process Form',exact:true}).click()
    recordId=(await (await creation).json()).record.id
    await page.waitForFunction(()=>document.querySelector('.u-review-heading')||document.querySelector('.u-processing h1')?.textContent==='This form needs another look',{},{timeout:210000})
    await expect(page.getByRole('heading',{name:'Review against the original'})).toBeVisible()
    const records=(await (await request.get('/api/u1/records')).json()).records
    let record=records.find((r:{id:string})=>r.id===recordId)
    expect(record.fields.find((f:{id:string})=>f.id==='year').value).toBe('2017')
    expect(record.fields.find((f:{id:string})=>f.id==='manufacturer').value).toBe('')
    expect(record.fields.find((f:{id:string})=>f.id==='design.mawp').value.replace(/\s/g,'')).toBe('50psi')
    expect(record.fields.find((f:{id:string})=>f.id==='tube.1.number').value).toBe('352')
    expect(record.fields.filter((f:{id:string})=>/^nozzle\.\d\.purpose$/.test(f.id))).toHaveLength(5)
    const year=record.fields.find((f:{id:string;box:[number,number,number,number]})=>f.id==='year')
    const sheet=page.locator('.u-document-sheet'),sheetBox=await sheet.boundingBox()
    expect(sheetBox).toBeTruthy()
    await page.mouse.click(sheetBox!.x+(year.box[0]+year.box[2]/2)*sheetBox!.width,sheetBox!.y+(year.box[1]+year.box[3]/2)*sheetBox!.height)
    await expect(page.locator('[data-field-id="year"]')).toHaveClass(/selected/)
    await expect(page.locator('.u-source-highlight')).toContainText('Year built')
    const flagged=record.fields.filter((f:{status:string;requirement?:string;page:number;box:[number,number,number,number]})=>f.requirement!=='ignored'&&['Review Required','Not Detected'].includes(f.status)).sort((a:{page:number;box:[number,number,number,number]},b:{page:number;box:[number,number,number,number]})=>a.page-b.page||a.box[1]-b.box[1]||a.box[0]-b.box[0])
    await page.getByRole('button',{name:/Review Required \(/}).click()
    const reviewList=page.getByRole('region',{name:'Fields requiring engineering review'})
    await expect(reviewList).toBeVisible()
    expect(await reviewList.locator('[data-review-field-id]').evaluateAll(elements=>elements.map(element=>(element as HTMLElement).dataset.reviewFieldId))).toEqual(flagged.map((f:{id:string})=>f.id))
    expect(await reviewList.locator('.u-review-required-page h3').allTextContents()).toEqual([...new Set(flagged.map((f:{page:number})=>f.page))].map(p=>expect.stringContaining(`Page ${p}`)))
    const firstPageTwo=flagged.findIndex((f:{page:number})=>f.page===2)
    expect(firstPageTwo).toBeGreaterThan(-1)
    await reviewList.locator('[data-review-field-id]').nth(firstPageTwo).click()
    await expect(page.getByAltText('Original Form U-1, page 2')).toBeVisible()
    await expect(page.locator(`[data-field-id="${flagged[firstPageTwo].id}"]`)).toHaveClass(/active|selected/)
    await page.getByRole('button',{name:/Review Required \(/}).click()
    await page.getByRole('button',{name:/Review Fields \(/}).click()
    await expect(page.locator('.u-review-queue-banner')).toContainText('Following the printed page and field order')
    await expect(page.locator('[data-field-id="manufacturer"]')).toHaveClass(/selected/)
    const queueTotal=Number((await page.locator('.u-review-queue-banner b').textContent())?.match(/of (\d+)/)?.[1])
    expect(queueTotal).toBeGreaterThan(1)
    await page.getByRole('button',{name:'Mark N/A & next',exact:true}).click()
    await expect(page.locator('.u-review-queue-banner')).toContainText(`2 of ${queueTotal}`)
    await expect(page.locator('[data-field-id="manufacturerAddress"]')).toHaveClass(/selected/)
    await expect(page.locator('[data-field-id="manufacturer"]')).toHaveCount(0)
    await page.getByRole('button',{name:'Exit Review Fields',exact:true}).click()
    await page.screenshot({path:'tmp/u1-tests/review-desktop.png',fullPage:true})
    await page.getByRole('button',{name:'Finish review',exact:true}).click()
    await expect(page.getByRole('button',{name:'Confirm Review & Approve',exact:true})).toBeEnabled()
    await expect(page.getByRole('heading',{name:'One final engineering confirmation'})).toBeVisible()
    await page.getByRole('button',{name:'Continue review',exact:true}).click()
    await expect(page.locator('.u-field-actions').getByRole('button',{name:'Confirm',exact:true})).toHaveCount(0)
    await page.getByLabel('Review section').selectOption('General information')
    await page.locator('[data-field-id="manufacturer"] .u-field-summary').click()
    await page.getByRole('textbox',{name:'Edit Manufacturer',exact:true}).fill('QA ENGINEERING LTD')
    await page.getByRole('button',{name:'Save correction',exact:true}).click()
    await expect(page.locator('.u-field.selected')).toContainText('Corrected')
    await page.getByRole('button',{name:'Flag',exact:true}).click()
    await expect(page.locator('.u-field.selected')).toContainText('Review Required')
    await page.getByRole('button',{name:'Mark N/A',exact:true}).click()
    await expect(page.locator('.u-field.selected .u-badge')).toHaveText('N/A')
    await page.getByLabel('Review section').selectOption('Nozzles / openings')
    await page.getByRole('button',{name:/Nozzles \/ openings row 1 Nozzle material:/}).click()
    await expect(page.locator('.u-source-highlight')).toBeVisible()
    await expect(page.getByAltText('Original Form U-1, page 2')).toBeVisible()
    await page.getByRole('textbox',{name:'Edit Nozzle material',exact:true}).fill('SA106-B')
    await page.getByRole('button',{name:'Save correction',exact:true}).click()
    await expect(page.locator('.u-table-editor')).toContainText('Corrected')
    await page.screenshot({path:'tmp/u1-tests/nozzles-desktop.png',fullPage:true})
    await page.getByRole('button',{name:'Corrections history',exact:true}).click()
    await expect(page.getByRole('heading',{name:'Review & corrections history'})).toBeVisible()
    await expect(page.locator('.u-data-table')).toContainText('SA106-B')
    await page.reload();await page.getByRole('button',{name:'Vessel records',exact:true}).click()
    await page.getByLabel('Search vessel records').fill(recordId)
    await page.getByRole('button',{name:recordId,exact:true}).click()
    await page.getByRole('button',{name:'Approval',exact:true}).click()
    await page.getByRole('button',{name:'Confirm Review & Approve',exact:true}).click()
    await expect(page.getByRole('heading',{name:'Approved · Ready for Database Entry'})).toBeVisible()
    record=(await (await request.get('/api/u1/records')).json()).records.find((r:{id:string})=>r.id===recordId)
    expect(record.fields.every((f:{status:string})=>['Verified','Corrected','N/A'].includes(f.status))).toBeTruthy()
    expect(record.fields.find((f:{id:string})=>f.id==='nozzle.1.material').status).toBe('Corrected')
    expect(record.fields.find((f:{id:string})=>f.id==='year').status).toBe('Verified')
    const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export JSON',exact:true}).click();const jsonDownload=await download;expect(jsonDownload.suggestedFilename()).toBe(recordId+'.json')
    const exported=JSON.parse(await readFile(await jsonDownload.path(),'utf8'))
    expect(exported.sections['Section 15'].tables['Table 1 · Heads'][0]).toHaveProperty('Knuckle radius')
    expect(exported.sections['Section 15'].tables['Table 2 · Body flanges on heads']).toBeDefined()
    expect(exported.sections['Section 19'].tables['Nozzles / openings'][0].Nozzle.Material).toBe('SA106-B')
    expect(exported.sections['Section 19'].tables['Nozzles / openings'][0].Reinforcement).toHaveProperty('Type')
    expect(exported.sections['Section 19'].tables['Nozzles / openings'][0].Reinforcement).toHaveProperty('Nozzle / flange attachment details')
    expect(exported.sections['Section 19'].tables['Nozzles / openings'][0].Flange).toHaveProperty('Type')
    const csv=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV',exact:true}).click();const csvDownload=await csv;expect(csvDownload.suggestedFilename()).toBe(recordId+'.csv')
    const csvLines=(await readFile(await csvDownload.path(),'utf8')).split('\r\n')
    expect(csvLines[0]).toBe('"Level","Form hierarchy","Value","Review status","OCR confidence","Source page"')
    const section15=csvLines.findIndex(line=>line.startsWith('"Section","Section 15 ·'))
    const table1=csvLines.findIndex((line,i)=>i>section15&&line.startsWith('"Table","  Table 1 · Heads"'))
    const knuckle=csvLines.findIndex((line,i)=>i>table1&&line.startsWith('"Field","      Knuckle radius"'))
    const table2=csvLines.findIndex((line,i)=>i>knuckle&&line.startsWith('"Table","  Table 2 · Body flanges on heads"'))
    expect(section15).toBeGreaterThan(0);expect(table1).toBeGreaterThan(section15);expect(knuckle).toBeGreaterThan(table1);expect(table2).toBeGreaterThan(knuckle)
    const section19=csvLines.findIndex(line=>line.startsWith('"Section","Section 19 ·'))
    const nozzle=csvLines.findIndex((line,i)=>i>section19&&line==='"Component","      Nozzle","","","",""')
    const reinforcement=csvLines.findIndex((line,i)=>i>nozzle&&line==='"Component","      Reinforcement","","","",""')
    const flange=csvLines.findIndex((line,i)=>i>reinforcement&&line==='"Component","      Flange","","","",""')
    expect(nozzle).toBeGreaterThan(section19);expect(reinforcement).toBeGreaterThan(nozzle);expect(flange).toBeGreaterThan(reinforcement)
    await page.getByRole('button',{name:'JSON',exact:true}).click();await expect(page.locator('.u-json')).toContainText('Section 19');await expect(page.locator('.u-json')).toContainText('Reinforcement');await expect(page.locator('.u-json')).toContainText('Section 15')
    await page.getByRole('button',{name:'Send to Database',exact:true}).click()
    await expect(page.getByRole('button',{name:'Database handoff recorded'})).toBeDisabled()
    const locked=await request.patch(`/api/u1/records/${recordId}`,{data:{action:'field',fieldId:'year',value:'2025',status:'Corrected'}});expect(locked.status()).toBe(400)
    await page.getByRole('button',{name:'Reopen for correction'}).click()
    await expect(page.getByRole('heading',{name:'Review against the original'})).toBeVisible()
    expect(errors).toEqual([])
  }finally{if(recordId)await unlink(path.join(process.cwd(),'.u1-data','records',recordId+'.json')).catch(()=>{})}
})

test('mobile capture intake and tablet layout stay within the viewport',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/')
  await page.screenshot({path:'tmp/u1-tests/dashboard-mobile.png',fullPage:true})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  await page.getByRole('button',{name:'Capture a new form'}).click()
  await expect(page.getByRole('button',{name:'Take Photos',exact:true})).toBeVisible()
  await page.screenshot({path:'tmp/u1-tests/capture-mobile.png',fullPage:true})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  await page.getByRole('button',{name:'Open navigation'}).click()
  await page.getByRole('button',{name:'Administration',exact:true}).click()
  await page.getByRole('button',{name:'Users & roles',exact:true}).click()
  await expect(page.getByLabel('Admin reviewer name')).toBeVisible()
  await page.setViewportSize({width:1024,height:900})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
})

test('camera capture, crop, rotate, retake and use-photo with simulated camera',async({browser})=>{
  const context=await browser.newContext({permissions:['camera']})
  const page=await context.newPage()
  await page.addInitScript(()=>{
    Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{
      const canvas=document.createElement('canvas');canvas.width=900;canvas.height=1200;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#273b32';ctx.fillRect(0,0,900,1200);ctx.fillStyle='white';ctx.fillRect(80,80,740,1040);ctx.fillStyle='black';ctx.font='24px Arial';ctx.fillText('FORM U-1 · CAMERA QA',120,150)
      const stream=canvas.captureStream(10);setInterval(()=>ctx.fillRect(120,170,1,1),100);return stream
    }})
  })
  await page.goto('/');await page.getByRole('button',{name:'Capture a new form'}).click();await page.getByRole('button',{name:'Take Photos',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Take Photos'})).toBeVisible()
  await page.waitForFunction(()=>!!document.querySelector('video')?.videoWidth)
  await page.getByRole('button',{name:'Capture page',exact:true}).click()
  await page.getByRole('button',{name:'Rotate 90°',exact:true}).click()
  await page.getByRole('button',{name:'Rotate 90°',exact:true}).click()
  await page.getByRole('button',{name:'Rotate 90°',exact:true}).click()
  await page.getByRole('button',{name:'Rotate 90°',exact:true}).click()
  await page.getByRole('button',{name:'Detect edges',exact:true}).click()
  await page.getByRole('button',{name:'Use Photo',exact:true}).click()
  await expect(page.locator('.u-page-tile')).toHaveCount(1)
  await page.getByRole('button',{name:'Preview page 1',exact:true}).click();await page.getByRole('button',{name:'Retake',exact:true}).click()
  await page.waitForFunction(()=>!!document.querySelector('video')?.videoWidth)
  await page.getByRole('button',{name:'Capture page',exact:true}).click();await page.getByRole('button',{name:'Use Photo',exact:true}).click()
  await expect(page.locator('.u-page-tile')).toHaveCount(1)
  await expect(page.getByRole('button',{name:'Process Form',exact:true})).toBeDisabled()
  await context.close()
})
