import { test, expect } from '@playwright/test'
import { unlink } from 'node:fs/promises'
import path from 'node:path'

test('real PDF extraction, engineering corrections, approval gate and exports',async({page,request})=>{
  test.setTimeout(300000)
  let recordId=''
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  try{
    await page.goto('/')
    await page.getByRole('button',{name:'Capture a new form'}).click()
    await expect(page.getByRole('button',{name:'Process Form',exact:true})).toBeDisabled()
    await page.locator('input[type=file][multiple]').setInputFiles('public/reference-u1.pdf')
    await expect(page.locator('.u-page-tile')).toHaveCount(3)
    await page.getByRole('button',{name:'Move page 1 later'}).click()
    await expect(page.locator('.u-page-tile').first()).toContainText('page 2')
    await page.getByRole('button',{name:'Move page 1 later'}).click()
    await page.getByRole('button',{name:'Preview page 1',exact:true}).click()
    await page.getByRole('button',{name:'Detect edges',exact:true}).click()
    await page.getByRole('button',{name:'Reset crop',exact:true}).click()
    await page.getByRole('button',{name:'Close preview',exact:true}).click()
    await page.getByLabel('Record name',{exact:true}).fill('QA reference · real OCR')
    const creation=page.waitForResponse(r=>r.url().endsWith('/api/u1/records')&&r.request().method()==='POST')
    await page.getByRole('button',{name:'Process Form',exact:true}).click()
    recordId=(await (await creation).json()).record.id
    await page.waitForFunction(()=>document.querySelector('.u-review-heading')||document.querySelector('.u-processing h1')?.textContent==='This form needs another look',{},{timeout:210000})
    await expect(page.getByRole('heading',{name:'Review against the original'})).toBeVisible()
    const records=(await (await request.get('/api/u1/records')).json()).records
    let record=records.find((r:{id:string})=>r.id===recordId)
    expect(record.fields.find((f:{id:string})=>f.id==='year').value).toBe('2017')
    expect(record.fields.find((f:{id:string})=>f.id==='manufacturer').value).toBe('')
    expect(record.fields.find((f:{id:string})=>f.id==='design.mawp').value.replace(/\s/g,'')).toBe('50psi')
    expect(record.fields.find((f:{id:string})=>f.id==='tube.1.number').value).toBe('352')
    expect(record.fields.filter((f:{id:string})=>/^nozzle\.\d\.purpose$/.test(f.id))).toHaveLength(5)
    await page.screenshot({path:'tmp/u1-tests/review-desktop.png',fullPage:true})
    const blocked=await request.patch(`/api/u1/records/${recordId}`,{data:{action:'approve',reviewer:'QA engineer'}})
    expect(blocked.status()).toBe(400)
    await page.getByRole('button',{name:'Review approval',exact:false}).click()
    await expect(page.getByRole('button',{name:'Approve Engineering Record',exact:true})).toBeDisabled()
    await page.getByRole('button',{name:'Continue review',exact:true}).click()
    await page.getByRole('textbox',{name:'Edit Manufacturer',exact:true}).fill('QA ENGINEERING LTD')
    await page.getByRole('button',{name:'Save correction',exact:true}).click()
    await expect(page.locator('.u-field.selected')).toContainText('Corrected')
    await page.getByRole('button',{name:'Flag',exact:true}).click()
    await expect(page.locator('.u-field.selected')).toContainText('Review Required')
    await page.getByRole('button',{name:'Mark N/A',exact:true}).click()
    await expect(page.locator('.u-field.selected .u-badge')).toHaveText('N/A')
    await page.getByLabel('Review section').selectOption('Nozzles / openings')
    await page.getByRole('button',{name:/Nozzles \/ openings row 1 Nozzle material:/}).click()
    await expect(page.locator('.u-source-highlight')).toBeVisible()
    await expect(page.getByAltText('Original Form U-1, page 2')).toBeVisible()
    await page.getByRole('textbox',{name:'Edit Nozzle material',exact:true}).fill('SA106-B')
    await page.getByRole('button',{name:'Save correction',exact:true}).click()
    await expect(page.locator('.u-table-editor')).toContainText('Corrected')
    await page.screenshot({path:'tmp/u1-tests/nozzles-desktop.png',fullPage:true})
    await page.getByRole('button',{name:'Corrections history',exact:true}).click()
    await expect(page.getByRole('heading',{name:'Review & corrections history'})).toBeVisible()
    await expect(page.locator('.u-data-table')).toContainText('SA106-B')
    record=(await (await request.get('/api/u1/records')).json()).records.find((r:{id:string})=>r.id===recordId)
    // Simulated explicit review decisions exercise the gate; this QA record is
    // removed in finally and is never represented as a real engineer sign-off.
    for(const f of record.fields){
      if(['Verified','Corrected','N/A'].includes(f.status))continue
      const response=await request.patch(`/api/u1/records/${recordId}`,{data:{action:'field',fieldId:f.id,value:f.value||'N/A',status:f.value?'Verified':'N/A',reviewer:'QA engineer'}})
      expect(response.ok()).toBeTruthy()
    }
    await page.reload();await page.getByRole('button',{name:'Vessel records',exact:true}).click()
    await page.getByLabel('Search vessel records').fill(recordId)
    await page.getByRole('button',{name:recordId,exact:true}).click()
    await page.getByRole('button',{name:'Approval',exact:true}).click()
    await page.getByRole('button',{name:'Approve Engineering Record',exact:true}).click()
    await expect(page.getByRole('heading',{name:'Approved · Ready for Database Entry'})).toBeVisible()
    const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export JSON',exact:true}).click();expect((await download).suggestedFilename()).toBe(recordId+'.json')
    const csv=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV',exact:true}).click();expect((await csv).suggestedFilename()).toBe(recordId+'.csv')
    await page.getByRole('button',{name:'JSON',exact:true}).click();await expect(page.locator('.u-json')).toContainText('Nozzles / openings')
    await page.getByRole('button',{name:'Send to Database',exact:true}).click()
    await expect(page.getByRole('button',{name:'Database handoff recorded'})).toBeDisabled()
    const locked=await request.patch(`/api/u1/records/${recordId}`,{data:{action:'field',fieldId:'year',value:'2025',status:'Corrected'}});expect(locked.status()).toBe(400)
    await page.getByRole('button',{name:'Reopen for correction'}).click()
    await expect(page.getByRole('heading',{name:'Review against the original'})).toBeVisible()
    expect(errors).toEqual([])
  }finally{if(recordId)await unlink(path.join(process.cwd(),'.u1-data','records',recordId+'.json')).catch(()=>{})}
})

test('mobile capture intake and tablet layout stay within the viewport',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/')
  await page.screenshot({path:'tmp/u1-tests/dashboard-mobile.png',fullPage:true})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  await page.getByRole('button',{name:'Capture a new form'}).click()
  await expect(page.getByRole('button',{name:'Take Photos',exact:true})).toBeVisible()
  await page.screenshot({path:'tmp/u1-tests/capture-mobile.png',fullPage:true})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  await page.getByRole('button',{name:'Open navigation'}).click()
  await page.getByRole('button',{name:'Administration',exact:true}).click()
  await page.getByRole('button',{name:'Users & roles',exact:true}).click()
  await expect(page.getByLabel('Admin reviewer name')).toBeVisible()
  await page.setViewportSize({width:1024,height:900})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
})

test('camera capture, crop, rotate, retake and use-photo with simulated camera',async({browser})=>{
  const context=await browser.newContext({permissions:['camera']})
  const page=await context.newPage()
  await page.addInitScript(()=>{
    Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{
      const canvas=document.createElement('canvas');canvas.width=900;canvas.height=1200;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#273b32';ctx.fillRect(0,0,900,1200);ctx.fillStyle='white';ctx.fillRect(80,80,740,1040);ctx.fillStyle='black';ctx.font='24px Arial';ctx.fillText('FORM U-1 · CAMERA QA',120,150)
      const stream=canvas.captureStream(10);setInterval(()=>ctx.fillRect(120,170,1,1),100);return stream
    }})
  })
  await page.goto('/');await page.getByRole('button',{name:'Capture a new form'}).click();await page.getByRole('button',{name:'Take Photos',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Take Photos'})).toBeVisible()
  await page.waitForFunction(()=>!!document.querySelector('video')?.videoWidth)
  await page.getByRole('button',{name:'Capture page',exact:true}).click()
  await page.getByRole('button',{name:'Rotate 90°',exact:true}).click()
  await page.getByRole('button',{name:'Rotate 90°',exact:true}).click()
  await page.getByRole('button',{name:'Rotate 90°',exact:true}).click()
  await page.getByRole('button',{name:'Rotate 90°',exact:true}).click()
  await page.getByRole('button',{name:'Detect edges',exact:true}).click()
  await page.getByRole('button',{name:'Use Photo',exact:true}).click()
  await expect(page.locator('.u-page-tile')).toHaveCount(1)
  await page.getByRole('button',{name:'Preview page 1',exact:true}).click();await page.getByRole('button',{name:'Retake',exact:true}).click()
  await page.waitForFunction(()=>!!document.querySelector('video')?.videoWidth)
  await page.getByRole('button',{name:'Capture page',exact:true}).click();await page.getByRole('button',{name:'Use Photo',exact:true}).click()
  await expect(page.locator('.u-page-tile')).toHaveCount(1)
  await expect(page.getByRole('button',{name:'Process Form',exact:true})).toBeDisabled()
  await context.close()
})
