import { test, expect } from '@playwright/test'

test('all seven role entries navigate to their workspace', async ({ page }) => {
  for (const [name, route] of [['Project Manager','command-center'],['Technical / Lab','technical'],['Operations','readiness'],['Commercial','cost-impact'],['Procurement / Logistics','readiness'],['Management','management'],['Admin','admin']]) {
    await page.goto('/')
    await page.getByRole('button', { name: new RegExp('^'+name.replaceAll('/', '\\/')) }).click()
    await page.getByRole('button', {name:'Enter Workspace'}).click()
    await expect(page).toHaveURL(new RegExp('/'+route+'$'))
  }
})
test('all project tabs and project setup persist', async ({ page }) => {
  for (const id of ['pwt-001','ptp-002','fpso-003','scf-004','opt-005']) {
    await page.goto('/projects/'+id)
    for (const tab of await page.getByRole('tab').all()) { await tab.click(); await expect(tab).toHaveAttribute('aria-selected','true'); await expect(page.getByRole('tabpanel')).toBeVisible() }
  }
  await page.goto('/projects/pwt-001/setup')
  await page.locator('#name').fill('Updated treatment project')
  await page.locator('#contact').fill('QA Client Contact')
  await page.getByRole('button',{name:'Save Changes'}).first().click()
  await expect(page.getByText('Project details saved',{exact:true})).toBeVisible()
  await page.goto('/projects/pwt-001')
  await expect(page.getByRole('heading',{level:1})).toHaveText('Updated treatment project')
  await page.reload()
  await expect(page.getByRole('heading',{level:1})).toHaveText('Updated treatment project')
  await page.goto('/projects/pwt-001/setup')
  await expect(page.locator('#contact')).toHaveValue('QA Client Contact')
})
test('invalid setup cannot report success', async ({ page }) => {
  await page.goto('/projects/pwt-001/setup')
  await page.locator('#name').fill('   ')
  await page.getByRole('button',{name:'Save Changes'}).first().click()
  await expect(page.getByText('Complete the required project details')).toBeVisible()
  await page.locator('#name').fill('Valid project')
  await page.locator('#forecast').fill('2020-01-01')
  await page.getByRole('button',{name:'Save Changes'}).first().click()
  await expect(page.getByText('Check the project dates')).toBeVisible()
})
test('approval updates related actions and persists without duplicates', async ({ page }) => {
  await page.goto('/changes/cr-003')
  await page.getByRole('button',{name:'Approve Change',exact:true}).click()
  await page.getByRole('button',{name:'Cancel',exact:true}).click()
  await expect(page.getByRole('button',{name:'Approve Change',exact:true})).toBeEnabled()
  await page.getByRole('button',{name:'Approve Change',exact:true}).click()
  await page.getByRole('button',{name:'Confirm Approval',exact:true}).click()
  await expect(page.getByText('Change approved',{exact:true})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button',{name:'Approve Change',exact:true})).toHaveCount(0)
  await page.goto('/actions')
  await expect(page.getByText('Update field execution plan for approved CR-003 scope',{exact:true})).toHaveCount(1)
  await page.goto('/timeline')
  await expect(page.getByText(/Shifts by \+3 days/).first()).toBeVisible()
})
for(const kind of ['reject','clarify','escalate']) test(`${kind} dialog validates and persists`, async ({page}) => {
  await page.goto('/changes/cr-003')
  const trigger={reject:'Reject',clarify:'Request Clarification',escalate:'Escalate'}[kind]
  await page.getByRole('button',{name:trigger,exact:true}).click()
  const dialog=page.getByRole('dialog')
  const confirm=dialog.getByRole('button',{name:kind==='reject'?'Confirm Reject':kind==='clarify'?'Confirm':'Confirm Escalation',exact:true})
  await expect(confirm).toBeDisabled()
  await dialog.getByRole('textbox').fill('   ')
  await expect(confirm).toBeDisabled()
  await dialog.getByRole('textbox').fill('The team must verify the secondary train scope.')
  await confirm.click()
  await page.reload()
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('meridian-v2:changes')!).find((c:any)=>c.id==='cr-003'))
  expect(saved.status).toBe({reject:'rejected',clarify:'clarification-requested',escalate:'escalated'}[kind])
  if(kind==='escalate'){await page.goto('/management');await expect(page.getByText('CR-003 Escalated')).toBeVisible()}
})
test('specialists cannot approve changes', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button',{name:/^Technical \/ Lab/}).click()
  await page.getByRole('button',{name:'Enter Workspace'}).click()
  await page.goto('/changes/cr-003')
  await expect(page.getByRole('button',{name:'Approve Change',exact:true})).toBeDisabled()
})
test('issue escalation and resolution update management and counts',async({page})=>{
  await page.goto('/issues')
  await page.getByRole('button',{name:'View',exact:true}).first().click()
  await page.getByRole('button',{name:'Escalate',exact:true}).click()
  await page.keyboard.press('Escape')
  await page.goto('/management')
  await expect(page.getByText('Escalated issue',{exact:true})).toBeVisible()
  await page.goto('/');await page.getByRole('button',{name:/^Procurement/}).click();await page.getByRole('button',{name:'Enter Workspace'}).click()
  await page.goto('/issues')
  await page.getByRole('button',{name:'View',exact:true}).first().click()
  await page.getByRole('button',{name:'Resolve',exact:true}).click()
  await page.reload()
  await expect(page.getByText('Resolved',{exact:true})).toBeVisible()
})
test('readiness, actions, and settings survive refresh',async({page})=>{
  await page.goto('/readiness')
  for(const button of await page.getByRole('button',{name:'Review',exact:true}).all()){
    await button.click();const ready=page.getByRole('button',{name:'Mark Ready',exact:true});if(await ready.isEnabled()){await ready.click();break}await page.keyboard.press('Escape')
  }
  await page.goto('/actions')
  await page.getByRole('button',{name:'Complete',exact:true}).and(page.locator(':enabled')).first().click()
  await page.getByRole('button',{name:'Undo',exact:true}).click()
  await page.getByRole('button',{name:'Complete',exact:true}).and(page.locator(':enabled')).first().click()
  await page.reload()
  await expect(page.getByText('Complete',{exact:true}).first()).toBeVisible()
  await page.goto('/settings')
  await expect(page.getByRole('heading',{level:1})).toHaveText('Role Responsibilities')
  await expect(page.getByRole('switch')).toHaveCount(0)
})
test('technical records are saved and found through global search',async({page})=>{
  await page.goto('/'); await page.getByRole('button',{name:/^Technical \/ Lab/}).click(); await page.getByRole('button',{name:'Enter Workspace'}).click()
  await page.goto('/technical')
  await page.getByRole('button',{name:/Sample \/ Technical Information Received/}).click()
  await page.getByRole('button',{name:'Add Technical Record',exact:true}).click()
  await page.locator('#record-name').fill('QA analysis record')
  await page.locator('#record-summary').fill('Secondary train analysis completed; review treatment dosage.')
  await page.getByRole('button',{name:'Save Record',exact:true}).click()
  await page.keyboard.press('Escape')
  await page.goto('/documents')
  await expect(page.getByText('QA analysis record',{exact:true})).toBeVisible()
  await page.reload()
  await page.getByRole('button',{name:'Search workspace',exact:true}).click()
  await page.getByRole('textbox',{name:'Search all records'}).fill('QA analysis record')
  await page.getByRole('dialog').getByRole('link').click()
  await expect(page.getByRole('dialog',{name:'QA analysis record',exact:true})).toContainText('Secondary train analysis completed')
})
test('admin profile, role, deactivate and reactivate persist',async({page})=>{
  await page.goto('/'); await page.getByRole('button',{name:/^Admin/}).click(); await page.getByRole('button',{name:'Enter Workspace'}).click()
  await page.goto('/admin/users')
  await page.getByRole('button',{name:'Actions for James Parker'}).click()
  await page.getByRole('menuitem',{name:'Edit Profile'}).click()
  await page.locator('#profile-name').fill('James Parker QA')
  await page.getByRole('button',{name:'Save Changes',exact:true}).click()
  await page.reload()
  await expect(page.getByText('James Parker QA',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Actions for James Parker QA'}).click()
  await page.getByRole('menuitem',{name:'Change Role'}).click()
  await page.getByRole('dialog').getByRole('combobox').click()
  await page.getByRole('option',{name:'Operations Lead',exact:true}).click()
  await page.getByRole('button',{name:'Confirm',exact:true}).click()
  await page.getByRole('button',{name:'Actions for James Parker QA'}).click()
  await page.getByRole('menuitem',{name:'Deactivate',exact:true}).click()
  await page.getByRole('button',{name:'Confirm Deactivate'}).click()
  await page.reload()
  await expect(page.getByText('Deactivated',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Actions for James Parker QA'}).click()
  await page.getByRole('menuitem',{name:'Reactivate',exact:true}).click()
  await expect(page.getByText('Deactivated',{exact:true})).toHaveCount(0)
})
test('search empty states, table sorting and mobile navigation',async({page})=>{
  for(const route of ['projects','changes','issues','documents','actions']){
    await page.goto('/'+route)
    await page.getByRole('textbox').first().fill('no-matching-record-xyz')
    await expect(page.getByText(new RegExp('No '+route+' match'))).toBeVisible()
  }
  await page.goto('/projects')
  await page.getByRole('button',{name:'Sort by Project',exact:true}).click()
  await expect(page.getByRole('columnheader').first()).toHaveAttribute('aria-sort','ascending')
  await page.setViewportSize({width:390,height:844})
  await page.getByRole('button',{name:'Open navigation'}).click()
  await page.getByRole('dialog').getByRole('link',{name:'Changes',exact:true}).click()
  await expect(page).toHaveURL(/\/changes$/)
  await expect(page.getByRole('dialog')).toHaveCount(0)
})
