'use client'
import { useState } from 'react'
import { ArrowDownToLine, ArrowRight, ArrowUpRight, CircleHelp, Database, History, ShieldCheck } from 'lucide-react'
import { exportRecord, fieldValue, resolved, type URecord } from '@/lib/u1/types'
import { Status } from './review'
export type View='dashboard'|'capture'|'processing'|'review'|'record'|'history'|'approval'|'records'|'export'|'admin'
export const date=(v:string)=>new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})
export function RecordTabs({view,go}:{view:View;go:(v:View)=>void}){return <div className="u-record-tabs">{[['review','Document review'],['record','Vessel record'],['history','Corrections history'],['approval','Approval'],['export','Database / export']].map(([id,label])=><button className={view===id?'active':''} key={id} onClick={()=>go(id as View)}>{label}</button>)}</div>}
export function RecordTable({records,open,compact=false}:{records:URecord[];open:(r:URecord,v?:View)=>void;compact?:boolean}){return <div className="u-table-scroll"><table className={`u-data-table ${compact?'u-compact-table':' '}`}><thead><tr><th>Record / manufacturer</th><th>Serial number</th>{!compact&&<><th>National Board</th><th>Year</th><th>MAWP</th><th>Form</th></>}<th>Review status</th>{!compact&&<><th>Reviewer</th><th>Approval</th></>}<th><span className="u-sr-only">Open record</span></th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td><button className="u-record-link" onClick={()=>open(r)}>{r.id}</button><small>{fieldValue(r,'manufacturer')==='—'?'Manufacturer not detected':fieldValue(r,'manufacturer')}</small></td><td><code>{fieldValue(r,'serial')}</code></td>{!compact&&<><td>{fieldValue(r,'nationalBoard')}</td><td>{fieldValue(r,'year')}</td><td>{fieldValue(r,'design.mawp')}</td><td>U-1</td></>}<td><Status status={r.status}/></td>{!compact&&<><td>{r.reviewer}</td><td>{r.approvedAt?'Approved':'Awaiting review'}</td></>}<td><button aria-label={`Open ${r.id}`} onClick={()=>open(r,r.approvedAt?'record':'review')}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>}
export function Structured({record}:{record:URecord}){
  const sections=[...new Set(record.fields.map(f=>f.section))]
  const [query,setQuery]=useState(''),[expanded,setExpanded]=useState<string[]>(['General information','Pressure / design','Nozzles / openings'])
  return <div className="u-structured">
    <div className="u-structure-tools"><label className="u-search"><input aria-label="Search structured fields" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a section, material or design value…"/></label><button className="u-text-btn" onClick={()=>setExpanded(sections)}>Expand all</button><button className="u-text-btn" onClick={()=>setExpanded([])}>Collapse all</button></div>
    {sections.filter(s=>record.fields.some(f=>f.section===s&&`${f.section} ${f.label} ${f.value}`.toLowerCase().includes(query.toLowerCase()))).map((section,i)=>{
      const fs=record.fields.filter(f=>f.section===section),tables=[...new Set(fs.filter(f=>f.table).map(f=>f.table!))],corrected=fs.filter(f=>f.status==='Corrected').length
      return <section className="u-structure-section" key={section}>
        <button className="u-structure-heading" aria-expanded={!!query||expanded.includes(section)} onClick={()=>setExpanded(prev=>prev.includes(section)?prev.filter(s=>s!==section):[...prev,section])}><span className="u-section-number">{String(i+1).padStart(2,'0')}</span><b role="heading" aria-level={2}>{section}</b><span>{fs.length} fields · {corrected} corrected</span><ArrowRight size={17}/></button>
        {(!!query||expanded.includes(section))&&<div className="u-structure-body">
          {!!fs.filter(f=>!f.table).length&&<dl className="u-definition-grid">{fs.filter(f=>!f.table).map(f=><div key={f.id}><dt>{f.label}</dt><dd>{f.value||<span className="u-missing-value">Not detected</span>}</dd><dd className="u-definition-status"><Status status={f.status}/></dd></div>)}</dl>}
          {tables.map(table=>{const cells=fs.filter(f=>f.table===table),rows=[...new Set(cells.map(f=>f.row!))],cols=[...new Set(cells.map(f=>f.label))];return <div className="u-structure-table" key={table}><h3>{table}</h3><div className="u-table-scroll" tabIndex={0} role="region" aria-label={table}><table className="u-data-table"><thead><tr><th>Row</th>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row}><td>{String(row).padStart(2,'0')}</td>{cols.map(col=>{const f=cells.find(f=>f.row===row&&f.label===col)!;return <td key={col} title={f.status}><span className={`u-record-cell ${resolved(f)?'resolved':'unresolved'}`}>{f.value||'—'}<span className="u-cell-dot"/></span></td>})}</tr>)}</tbody></table></div></div>})}
        </div>}
      </section>
    })}
    {!record.fields.some(f=>`${f.section} ${f.label} ${f.value}`.toLowerCase().includes(query.toLowerCase()))&&<div className="u-empty"><CircleHelp/><h3>No matching fields</h3><p>Try a section name or clear your search.</p></div>}
  </div>
}
export function HistoryView({records,activeId,setActiveId}:{records:URecord[];activeId:string;setActiveId:(s:string)=>void}){
 const events=records.flatMap(r=>r.history.map(h=>({...h,recordId:r.id}))).sort((a,b)=>b.at.localeCompare(a.at)).filter(h=>!activeId||h.recordId===activeId)
 return <><div className="u-heading"><div><div className="u-eyebrow">TRACEABILITY / ENGINEERING AUDIT</div><h1>Review & corrections history</h1><p>Original extraction, subsequent changes and approval decisions.</p></div><select aria-label="History record" value={activeId} onChange={e=>setActiveId(e.target.value)}><option value="">All records</option>{records.map(r=><option key={r.id} value={r.id}>{r.id}</option>)}</select></div><section className="u-card u-table-scroll"><table className="u-data-table"><thead><tr><th>Field / record</th><th>Originally extracted</th><th>Previous value</th><th>Reviewed value</th><th>Reviewer / date</th><th>Status</th></tr></thead><tbody>{events.map(h=>{const r=records.find(r=>r.id===h.recordId),f=r?.fields.find(f=>f.id===h.field);return <tr key={h.id}><td><b>{f?.label||h.field}</b><small>{h.recordId}{f?.row?` · row ${f.row}`:''}</small></td><td><code>{f?.original||'—'}</code></td><td>{h.before||'(blank)'}</td><td><code>{h.after||'(blank)'}</code></td><td>{h.reviewer}<small>{new Date(h.at).toLocaleString()}</small></td><td><Status status={h.status}/></td></tr>})}</tbody></table>{!events.length&&<div className="u-empty"><History/><p>No review history yet.</p></div>}</section></>
}
export function ApprovalView({record:r,reviewer,setReviewer,busy,patch,go}:{record:URecord;reviewer:string;setReviewer:(s:string)=>void;busy:boolean;patch:(b:Record<string,unknown>)=>void;go:(v:View)=>void}){
 const unchanged=r.fields.filter(f=>!['Corrected','N/A'].includes(f.status)&&!!f.value).length,corrected=r.fields.filter(f=>f.status==='Corrected').length,attention=r.fields.filter(f=>['Review Required','Not Detected'].includes(f.status)).length,blank=r.fields.filter(f=>!f.value).length,na=r.fields.filter(f=>f.status==='N/A').length
 return <><div className="u-heading"><div><div className="u-eyebrow">ENGINEERING SIGN-OFF / {r.id}</div><h1>Confirm engineering review</h1><p>One confirmation accepts the reviewed record and prepares it for database entry.</p></div><ShieldCheck size={35}/></div><div className="u-approval-metrics">{[['Total fields',r.fields.length],['Unchanged values',unchanged],['Corrected',corrected],['Needs attention',attention],['Blank values',blank],['Already N/A',na]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><section className="u-card u-signoff"><div className="u-icon-block"><ShieldCheck size={29}/></div><h2>One final engineering confirmation</h2><p>Confirm that you compared the extracted record with the original document. Unchanged values will be verified, saved corrections will remain corrected, and blank fields will be recorded as N/A.</p><label>Review engineer<input aria-label="Review engineer" value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><div className="u-crop-tools"><button className="u-btn" onClick={()=>go('review')}>Continue review</button><button className="u-btn primary" disabled={busy||!r.fields.length||!reviewer.trim()||!!r.approvedAt} onClick={()=>patch({action:'approve'})}><ShieldCheck size={17}/>Confirm Review & Approve</button></div><small>This confirmation accepts every value as currently shown and records one engineering sign-off.</small></section></>
}
export function ExportView({record:r,busy,patch,go,notify}:{record:URecord;busy:boolean;patch:(b:Record<string,unknown>)=>void;go:(v:View)=>void;notify:(s:string)=>void}){
 const [tab,setTab]=useState('Table')
 function download(kind:'json'|'csv'){const quote=(s:unknown)=>'"'+String(s??'').replaceAll('"','""')+'"';const contents=kind==='json'?JSON.stringify(exportRecord(r),null,2):[['Section','Table','Row','Field','Value','Review status','OCR confidence','Source page'],...r.fields.map(f=>[f.section,f.table||'',f.row||'',f.label,/^[=+@\-\t\r]/.test(f.value)?"'"+f.value:f.value,f.status,f.confidence,f.page])].map(row=>row.map(quote).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([contents],{type:kind==='json'?'application/json':'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`${r.id}.${kind}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify(`${kind.toUpperCase()} exported.`)}
 return <><div className="u-heading"><div><div className="u-eyebrow">DATABASE HANDOFF / {r.id}</div><h1>{r.approvedAt?'Approved · Ready for Database Entry':'Structured data preview'}</h1><p>{r.approvedAt?`Approved by ${r.reviewer} on ${date(r.approvedAt)}`:'Complete engineering approval to enable export and database handoff.'}</p></div><Status status={r.status}/></div>{!r.approvedAt&&<div className="u-warning"><CircleHelp size={19}/>This record still requires engineering approval.<button className="u-text-btn" onClick={()=>go('approval')}>Review approval<ArrowRight size={15}/></button></div>}<section className="u-card"><div className="u-card-head"><div className="u-segmented">{['Table','JSON'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div><span className="u-subtle">{r.fields.length} fields · {r.pages.length} source pages</span></div>{tab==='JSON'?<pre className="u-json">{JSON.stringify(exportRecord(r),null,2)}</pre>:<div className="u-export-table"><Structured record={r}/></div>}<div className="u-export-actions"><button className="u-btn" disabled={!r.approvedAt} onClick={()=>download('csv')}><ArrowDownToLine size={16}/>Export CSV</button><button className="u-btn" disabled={!r.approvedAt} onClick={()=>download('json')}><ArrowDownToLine size={16}/>Export JSON</button><button className="u-btn primary" disabled={!r.approvedAt||busy||!!r.databaseReceipt} onClick={()=>patch({action:'database'})}><Database size={16}/>{r.databaseReceipt?'Database handoff recorded':'Send to Database'}</button></div></section><div className="u-bottom-note"><Database size={19}/><p>{r.databaseReceipt?`Simulated receipt: ${r.databaseReceipt}. No external database was contacted.`:'CSV and JSON downloads are functional. Send to Database demonstrates a simulated integration.'}</p>{r.approvedAt&&<button disabled={busy} onClick={()=>patch({action:'reopen'})}>Reopen for correction</button>}</div></>
}


