import type {
  ActionItem,
  ActivityEntry,
  Change,
  DocumentRecord,
  Issue,
  Milestone,
  Person,
  Project,
  ReadinessItem,
  TechnicalStage,
} from "./types"

export const PEOPLE: Person[] = [
  { id: "james-parker", name: "James Parker", initials: "JP", role: "Project Manager", team: "Project Management" },
  { id: "omar-rahman", name: "Dr. Omar Rahman", initials: "OR", role: "Lead Lab Scientist", team: "Technical / Lab" },
  { id: "priya-nair", name: "Priya Nair", initials: "PN", role: "Technical Engineer", team: "Technical / Lab" },
  { id: "john-miller", name: "John Miller", initials: "JM", role: "Operations Lead", team: "Operations" },
  { id: "carlos-diaz", name: "Carlos Diaz", initials: "CD", role: "Field Superintendent", team: "Operations" },
  { id: "sara-malik", name: "Sara Malik", initials: "SM", role: "Procurement Lead", team: "Procurement / Logistics" },
  { id: "hassan-tariq", name: "Hassan Tariq", initials: "HT", role: "Logistics Coordinator", team: "Procurement / Logistics" },
  { id: "michael-grant", name: "Michael Grant", initials: "MG", role: "Commercial Manager", team: "Commercial" },
  { id: "emma-lewis", name: "Emma Lewis", initials: "EL", role: "VP Operations", team: "Management" },
  { id: "admin-user", name: "Admin User", initials: "AU", role: "System Administrator", team: "Admin" },
  { id: "client-contact", name: "Robert Hayes", initials: "RH", role: "Client Technical Lead, Gulf Energy", team: "Client" },
]

export const personById = (id: string): Person =>
  PEOPLE.find((p) => p.id === id) ?? {
    id,
    name: "Unassigned",
    initials: "—",
    role: "Unassigned",
    team: "Project Management",
  }

export const PRIMARY_PROJECT_ID = "pwt-001"

export const PROJECTS: Project[] = [
  {
    id: "pwt-001",
    name: "Produced Water Treatment Optimization",
    client: "Gulf Energy Corporation",
    facility: "North Field Processing Facility",
    projectManagerId: "james-parker",
    projectType: "Produced Water Treatment Optimization",
    scopeSummary:
      "Optimize chemical treatment program for produced water handling at the North Field Processing Facility, including laboratory characterization, treatment testing, and field-verified performance improvement.",
    startDate: "2026-09-01",
    promisedCompletion: "2026-09-27",
    forecastCompletion: "2026-09-30",
    currentPhase: "Execution Readiness",
    health: "at-risk",
    progress: 61,
    scheduleVarianceDays: 3,
    costExposure: 18500,
    status: "Active",
  },
  {
    id: "ptp-002",
    name: "Pipeline Treatment Performance Improvement",
    client: "Meridian Pipeline Systems",
    facility: "Sabine Pass Pump Station",
    projectManagerId: "james-parker",
    projectType: "Pipeline Treatment Performance",
    scopeSummary: "Corrosion and scale inhibitor performance improvement program across three pump stations.",
    startDate: "2026-08-11",
    promisedCompletion: "2026-09-25",
    forecastCompletion: "2026-10-02",
    currentPhase: "Field Execution",
    health: "at-risk",
    progress: 74,
    scheduleVarianceDays: 7,
    costExposure: 0,
    status: "Active",
  },
  {
    id: "fpso-003",
    name: "FPSO Chemical Treatment Evaluation",
    client: "Meridian Offshore Partners",
    facility: "FPSO Atlas Voyager",
    projectManagerId: "james-parker",
    projectType: "Chemical Treatment Evaluation",
    scopeSummary: "Shipboard chemical treatment evaluation for topside process water on the Atlas Voyager FPSO.",
    startDate: "2026-08-01",
    promisedCompletion: "2026-09-18",
    forecastCompletion: "2026-09-26",
    currentPhase: "Client Technical Review",
    health: "at-risk",
    progress: 68,
    scheduleVarianceDays: 8,
    costExposure: 0,
    status: "Active",
  },
  {
    id: "scf-004",
    name: "Scale Control Field Trial",
    client: "Desert Basin Resources",
    facility: "Basin 7 Wellpad Cluster",
    projectManagerId: "james-parker",
    projectType: "Scale Control Field Trial",
    scopeSummary: "Field trial of next-generation scale inhibitor across a six-well cluster.",
    startDate: "2026-07-20",
    promisedCompletion: "2026-09-10",
    forecastCompletion: "2026-09-10",
    currentPhase: "Technical Completion",
    health: "on-track",
    progress: 92,
    scheduleVarianceDays: 0,
    costExposure: 0,
    status: "Active",
  },
  {
    id: "opt-005",
    name: "Offshore Process Treatment Optimization",
    client: "Gulf Energy Corporation",
    facility: "West Cameron Platform",
    projectManagerId: "james-parker",
    projectType: "Process Treatment Optimization",
    scopeSummary: "Process treatment optimization for produced fluids handling on the West Cameron platform.",
    startDate: "2026-06-02",
    promisedCompletion: "2026-08-15",
    forecastCompletion: "2026-08-15",
    currentPhase: "Project Closure",
    health: "complete",
    progress: 100,
    scheduleVarianceDays: 0,
    costExposure: 0,
    status: "Closed",
  },
]

export const projectById = (id: string) => PROJECTS.find((p) => p.id === id)

// ---------- Technical Workflow (pwt-001) ----------
export const TECHNICAL_STAGES: TechnicalStage[] = [
  {
    id: "stage-1",
    name: "Sample / Technical Information Received",
    status: "completed",
    team: "Technical / Lab",
    assignedPersonId: "omar-rahman",
    startDate: "2026-09-01",
    completedDate: "2026-09-03",
    outcome: "Produced water samples and client technical requirement received and logged.",
    linkedDocumentId: "doc-1",
  },
  {
    id: "stage-2",
    name: "Lab Characterization",
    status: "completed",
    team: "Technical / Lab",
    assignedPersonId: "omar-rahman",
    startDate: "2026-09-06",
    completedDate: "2026-09-08",
    dependency: "Sample / Technical Information Received",
    outcome: "Water chemistry characterization complete and assessment recorded.",
    linkedDocumentId: "doc-2",
  },
  {
    id: "stage-3",
    name: "Treatment Test",
    status: "completed",
    team: "Technical / Lab",
    assignedPersonId: "priya-nair",
    startDate: "2026-09-08",
    completedDate: "2026-09-10",
    dependency: "Lab Characterization",
    outcome: "Treatment testing record completed; candidate chemistries shortlisted.",
    linkedDocumentId: "doc-3",
  },
  {
    id: "stage-4",
    name: "Technical Evaluation",
    status: "completed",
    team: "Technical / Lab",
    assignedPersonId: "omar-rahman",
    startDate: "2026-09-10",
    completedDate: "2026-09-11",
    dependency: "Treatment Test",
    outcome: "Technical evaluation complete. Recommended treatment program documented.",
  },
  {
    id: "stage-5",
    name: "Technical Proposal",
    status: "at-risk",
    team: "Technical / Lab",
    assignedPersonId: "omar-rahman",
    startDate: "2026-09-11",
    dueDate: "2026-09-13",
    dependency: "Technical Evaluation",
    waitingOn: "Client Sample Information (additional scope)",
    impactIfDelayed: "Client technical review and execution readiness may move by 2 days.",
    linkedDocumentId: "doc-5",
  },
  {
    id: "stage-6",
    name: "Client Technical Review",
    status: "not-started",
    team: "Client",
    assignedPersonId: "client-contact",
    dueDate: "2026-09-14",
    dependency: "Technical Proposal",
    impactIfDelayed: "Execution Readiness cannot begin until client technical approval is received.",
  },
  {
    id: "stage-7",
    name: "Pilot / Field Validation",
    status: "not-started",
    team: "Operations",
    assignedPersonId: "carlos-diaz",
    dueDate: "2026-09-20",
    dependency: "Client Technical Review",
  },
  {
    id: "stage-8",
    name: "Execution Ready",
    status: "not-started",
    team: "Operations",
    assignedPersonId: "john-miller",
    dueDate: "2026-09-16",
    dependency: "Client Technical Review",
  },
]

// ---------- Execution Readiness ----------
export const READINESS_ITEMS: ReadinessItem[] = [
  {
    id: "rd-1",
    name: "Technical Readiness",
    status: "ready",
    team: "Technical / Lab",
    assignedPersonId: "omar-rahman",
    dueDate: "2026-09-13",
    dependency: "Technical Evaluation complete",
    latestUpdate: "Technical evaluation and recommended treatment program complete.",
  },
  {
    id: "rd-2",
    name: "Material / Chemical Availability",
    status: "at-risk",
    team: "Procurement / Logistics",
    assignedPersonId: "sara-malik",
    dueDate: "2026-09-15",
    dependency: "Supplier delivery confirmation",
    issue: "Additional treatment chemical required after CR-003 scope change.",
    impact: "Mobilization may slip by 2 days if delivery is not expedited.",
    nextAction: "Confirm expedited delivery window with Gulf Chemical Trading.",
    relatedChangeId: "cr-003",
    relatedIssueId: "iss-1",
  },
  {
    id: "rd-3",
    name: "Equipment Readiness",
    status: "ready",
    team: "Operations",
    assignedPersonId: "carlos-diaz",
    dueDate: "2026-09-14",
    dependency: "None",
    latestUpdate: "Injection skid and dosing equipment inspected and staged.",
  },
  {
    id: "rd-4",
    name: "Manpower Readiness",
    status: "in-progress",
    team: "Operations",
    assignedPersonId: "john-miller",
    dueDate: "2026-09-17",
    dependency: "Confirmed execution window",
    latestUpdate: "Field crew schedule extension in progress to cover additional 3 days.",
    nextAction: "Confirm field crew schedule for extended execution window.",
    relatedChangeId: "cr-003",
  },
  {
    id: "rd-5",
    name: "Procurement Readiness",
    status: "at-risk",
    team: "Procurement / Logistics",
    assignedPersonId: "sara-malik",
    dueDate: "2026-09-15",
    dependency: "Material / Chemical Availability",
    issue: "Purchase order for additional chemical quantity pending confirmation.",
    impact: "Delay could push mobilization past 18 Sep.",
    nextAction: "Issue revised purchase order to Gulf Chemical Trading.",
    relatedChangeId: "cr-003",
  },
  {
    id: "rd-6",
    name: "Logistics Readiness",
    status: "in-progress",
    team: "Procurement / Logistics",
    assignedPersonId: "hassan-tariq",
    dueDate: "2026-09-16",
    dependency: "Material / Chemical Availability",
    latestUpdate: "Transport booked pending confirmed delivery date.",
  },
  {
    id: "rd-7",
    name: "Client Approval",
    status: "blocked",
    team: "Client",
    assignedPersonId: "client-contact",
    dueDate: "2026-09-14",
    dependency: "Technical Proposal",
    issue: "Client technical approval overdue pending revised technical proposal.",
    impact: "Execution Readiness blocked until approval is received.",
    nextAction: "Follow up with Gulf Energy technical team once revised proposal is submitted.",
  },
  {
    id: "rd-8",
    name: "Site Access",
    status: "ready",
    team: "Operations",
    assignedPersonId: "carlos-diaz",
    dueDate: "2026-09-14",
    dependency: "None",
    latestUpdate: "Site access permit confirmed with facility operator.",
  },
  {
    id: "rd-9",
    name: "Mobilization Readiness",
    status: "at-risk",
    team: "Operations",
    assignedPersonId: "john-miller",
    dueDate: "2026-09-18",
    dependency: "Material / Chemical Availability, Client Approval",
    issue: "Mobilization depends on chemical delivery and client sign-off.",
    impact: "Mobilization at risk of slipping 2-3 days.",
    nextAction: "Re-confirm mobilization date once chemical delivery and approval are locked.",
    relatedChangeId: "cr-003",
  },
]

// ---------- Timeline / Milestones ----------
export const MILESTONES: Milestone[] = [
  {
    id: "ms-1",
    name: "Contract Award",
    originalDate: "2026-09-01",
    forecastDate: "2026-09-01",
    status: "completed",
    team: "Commercial",
    daysImpacted: 0,
  },
  {
    id: "ms-2",
    name: "Technical Preparation",
    originalDate: "2026-09-03",
    forecastDate: "2026-09-03",
    status: "completed",
    team: "Technical / Lab",
    daysImpacted: 0,
  },
  {
    id: "ms-3",
    name: "Sample / Analysis",
    originalDate: "2026-09-08",
    forecastDate: "2026-09-08",
    status: "completed",
    team: "Technical / Lab",
    daysImpacted: 0,
  },
  {
    id: "ms-4",
    name: "Technical Proposal",
    originalDate: "2026-09-13",
    forecastDate: "2026-09-13",
    status: "at-risk",
    team: "Technical / Lab",
    dependency: "Client Sample Information",
    daysImpacted: 0,
  },
  {
    id: "ms-5",
    name: "Client Approval",
    originalDate: "2026-09-14",
    forecastDate: "2026-09-14",
    status: "delayed",
    team: "Client",
    dependency: "Technical Proposal",
    delayReason: "Awaiting revised technical proposal following CR-003.",
    daysImpacted: 0,
  },
  {
    id: "ms-6",
    name: "Execution Readiness",
    originalDate: "2026-09-16",
    forecastDate: "2026-09-16",
    status: "at-risk",
    team: "Operations",
    dependency: "Client Approval",
    daysImpacted: 0,
  },
  {
    id: "ms-7",
    name: "Mobilization",
    originalDate: "2026-09-18",
    forecastDate: "2026-09-18",
    status: "at-risk",
    team: "Operations",
    dependency: "Execution Readiness",
    daysImpacted: 0,
  },
  {
    id: "ms-8",
    name: "Field Execution",
    originalDate: "2026-09-20",
    forecastDate: "2026-09-20",
    status: "upcoming",
    team: "Operations",
    dependency: "Mobilization",
    daysImpacted: 0,
  },
  {
    id: "ms-9",
    name: "Performance Verification",
    originalDate: "2026-09-25",
    forecastDate: "2026-09-25",
    status: "upcoming",
    team: "Technical / Lab",
    dependency: "Field Execution",
    daysImpacted: 0,
  },
  {
    id: "ms-10",
    name: "Technical Completion",
    originalDate: "2026-09-27",
    forecastDate: "2026-09-27",
    status: "upcoming",
    team: "Technical / Lab",
    dependency: "Performance Verification",
    daysImpacted: 0,
  },
  {
    id: "ms-11",
    name: "Client Validation",
    originalDate: "2026-09-29",
    forecastDate: "2026-09-29",
    status: "upcoming",
    team: "Client",
    dependency: "Technical Completion",
    daysImpacted: 0,
  },
  {
    id: "ms-12",
    name: "Project Closure",
    originalDate: "2026-10-01",
    forecastDate: "2026-10-01",
    status: "upcoming",
    team: "Project Management",
    dependency: "Client Validation",
    daysImpacted: 0,
  },
]

// ---------- Changes ----------
export const CHANGES: Change[] = [
  {
    id: "cr-003",
    title: "Additional Treatment Scope Requested",
    source: "Client",
    dateRequested: "2026-09-11",
    status: "awaiting-pm-decision",
    highImpact: true,
    originalScope: "Chemical treatment optimization limited to primary separator train produced water stream.",
    requestedChange:
      "Extend treatment optimization scope to include the secondary separator train, requiring additional sample analysis, additional chemical volume, and extended field execution.",
    reason: "Client identified secondary train scaling issues during routine facility inspection and requested it be addressed within the same mobilization.",
    requestedBy: "Robert Hayes, Gulf Energy Corporation",
    affectedMilestoneIds: ["ms-8", "ms-10", "ms-11"],
    assessments: {
      technical: {
        team: "Technical / Lab",
        ownerLabel: "Technical / Lab",
        assignedPersonId: "omar-rahman",
        assessment:
          "Additional sample assessment required for the secondary train. Technical proposal must be updated to include revised dosing recommendation.",
        status: "complete",
        extra: { Impact: "Technical proposal update required." },
      },
      procurement: {
        team: "Procurement / Logistics",
        ownerLabel: "Procurement / Logistics",
        assignedPersonId: "sara-malik",
        assessment: "Additional chemical quantity required to cover secondary train dosing for the extended execution window.",
        status: "complete",
        extra: {
          Supplier: "Gulf Chemical Trading",
          Availability: "Confirmed with 2-day lead-time extension.",
        },
      },
      operations: {
        team: "Operations",
        ownerLabel: "Operations",
        assignedPersonId: "john-miller",
        assessment: "Additional treatment activity adds approximately 3 field execution days to cover the secondary train.",
        status: "complete",
        extra: { Equipment: "Available", Manpower: "Requires schedule extension" },
      },
      commercial: {
        team: "Commercial",
        ownerLabel: "Commercial",
        assignedPersonId: "michael-grant",
        assessment: "Additional cost exposure reviewed and confirmed against awarded commercial scope.",
        status: "complete",
        extra: { "Additional Cost Exposure": "$18,500" },
      },
    },
    combinedImpact: {
      scheduleDays: 3,
      cost: 18500,
      originalCompletion: "2026-09-27",
      forecastCompletion: "2026-09-30",
    },
  },
  {
    id: "cr-004",
    title: "Extended Sampling Frequency Request",
    source: "Client",
    dateRequested: "2026-09-05",
    status: "approved",
    highImpact: false,
    originalScope: "Weekly produced water sampling for the duration of the optimization program.",
    requestedChange: "Increase sampling frequency to twice weekly for the primary separator train.",
    reason: "Client wants tighter visibility into chemistry trends ahead of the treatment test phase.",
    requestedBy: "Robert Hayes, Gulf Energy Corporation",
    affectedMilestoneIds: ["ms-3"],
    assessments: {
      technical: {
        team: "Technical / Lab",
        ownerLabel: "Technical / Lab",
        assignedPersonId: "omar-rahman",
        assessment: "No additional lab capacity issue; sampling plan can accommodate.",
        status: "complete",
      },
      procurement: {
        team: "Procurement / Logistics",
        ownerLabel: "Procurement / Logistics",
        assignedPersonId: "sara-malik",
        assessment: "No additional material required.",
        status: "complete",
      },
      operations: {
        team: "Operations",
        ownerLabel: "Operations",
        assignedPersonId: "john-miller",
        assessment: "Minor additional field time for sample collection; absorbed into existing schedule.",
        status: "complete",
      },
      commercial: {
        team: "Commercial",
        ownerLabel: "Commercial",
        assignedPersonId: "michael-grant",
        assessment: "No material cost impact identified.",
        status: "complete",
      },
    },
    combinedImpact: {
      scheduleDays: 0,
      cost: 0,
      originalCompletion: "2026-09-27",
      forecastCompletion: "2026-09-27",
    },
    pmDecision: {
      status: "approved",
      note: "Approved — negligible impact, supports better chemistry visibility.",
      decidedBy: "James Parker",
      decidedAt: "2026-09-06 10:20",
    },
  },
]

// ---------- Issues ----------
export const ISSUES: Issue[] = [
  {
    id: "iss-1",
    title: "Chemical Delivery Delay",
    category: "Procurement",
    severity: "high",
    raisedBy: "Sara Malik",
    team: "Procurement / Logistics",
    assignedPersonId: "sara-malik",
    dateRaised: "2026-09-10",
    dueDate: "2026-09-15",
    affectedMilestone: "Mobilization",
    timelineImpact: "+2 Days",
    costImpact: "$0",
    status: "at-risk",
    pmAttention: true,
    description:
      "Gulf Chemical Trading has indicated a 2-day lead-time extension on the additional treatment chemical required for CR-003. Mobilization is at risk of slipping if delivery is not expedited.",
    waitingOn: "Supplier delivery confirmation",
    requiredAction: "Confirm expedited delivery window with Gulf Chemical Trading.",
    relatedChangeId: "cr-003",
  },
  {
    id: "iss-2",
    title: "Client Technical Approval Delay",
    category: "Client Dependency",
    severity: "critical",
    raisedBy: "Dr. Omar Rahman",
    team: "Technical / Lab",
    assignedPersonId: "omar-rahman",
    dateRaised: "2026-09-12",
    dueDate: "2026-09-14",
    affectedMilestone: "Client Approval",
    timelineImpact: "At Risk",
    costImpact: "$0",
    status: "overdue",
    pmAttention: true,
    description:
      "Client technical approval is overdue pending the revised technical proposal that incorporates the CR-003 secondary train scope. Execution Readiness cannot proceed until approval is received.",
    waitingOn: "Client Technical Review",
    requiredAction: "Submit revised technical proposal to unblock client review.",
    relatedChangeId: "cr-003",
  },
  {
    id: "iss-3",
    title: "Incomplete Client Sample Information",
    category: "Technical",
    severity: "medium",
    raisedBy: "Dr. Omar Rahman",
    team: "Technical / Lab",
    assignedPersonId: "omar-rahman",
    dateRaised: "2026-09-11",
    dueDate: "2026-09-13",
    affectedMilestone: "Technical Proposal",
    timelineImpact: "Proposal Due Tomorrow",
    costImpact: "$0",
    status: "waiting-for-input",
    pmAttention: true,
    description:
      "Secondary train sample metadata (collection point, flow conditions) from the client is incomplete, delaying finalization of the revised technical proposal.",
    waitingOn: "Client Sample Information",
    requiredAction: "Request complete sample metadata from client technical contact.",
    relatedChangeId: "cr-003",
  },
  {
    id: "iss-4",
    title: "Additional Sample Analysis Required",
    category: "Technical",
    severity: "medium",
    raisedBy: "Priya Nair",
    team: "Technical / Lab",
    assignedPersonId: "priya-nair",
    dateRaised: "2026-09-11",
    dueDate: "2026-09-16",
    affectedMilestone: "Sample / Analysis",
    timelineImpact: "None",
    costImpact: "$0",
    status: "in-review",
    pmAttention: false,
    description: "Secondary train samples require an additional characterization pass before the treatment test phase.",
    waitingOn: "Lab capacity scheduling",
    requiredAction: "Schedule additional characterization run this week.",
    relatedChangeId: "cr-003",
  },
]

// ---------- Actions ----------
export const ACTIONS: ActionItem[] = [
  {
    id: "act-1",
    title: "Confirm additional chemical availability",
    linkedItem: "CR-003 · Additional Treatment Scope",
    linkedHref: "/changes/cr-003",
    team: "Procurement / Logistics",
    assignedPersonId: "sara-malik",
    coordinatorId: "james-parker",
    dueDate: "2026-09-15",
    status: "in-progress",
    waitingOn: "Supplier",
    priority: "high",
    impactIfLate: "Mobilization slips by 2+ days.",
    nextStep: "Confirm expedited delivery window with Gulf Chemical Trading.",
  },
  {
    id: "act-2",
    title: "Submit revised technical proposal",
    linkedItem: "Technical Proposal Stage",
    linkedHref: "/technical",
    team: "Technical / Lab",
    assignedPersonId: "omar-rahman",
    coordinatorId: "james-parker",
    dueDate: "2026-09-13",
    status: "overdue",
    waitingOn: "Client Sample Information",
    priority: "high",
    impactIfLate: "Client technical review and Execution Readiness delayed further.",
    nextStep: "Finalize dosing recommendation for secondary train and resubmit.",
  },
  {
    id: "act-3",
    title: "Confirm field crew schedule extension",
    linkedItem: "Manpower Readiness",
    linkedHref: "/readiness",
    team: "Operations",
    assignedPersonId: "john-miller",
    coordinatorId: "james-parker",
    dueDate: "2026-09-17",
    status: "in-progress",
    waitingOn: "Internal scheduling",
    priority: "medium",
    impactIfLate: "Mobilization crew unavailable for extended execution window.",
    nextStep: "Lock crew roster for the extended 3-day execution window.",
  },
  {
    id: "act-4",
    title: "Obtain client technical approval",
    linkedItem: "Client Technical Review",
    linkedHref: "/technical",
    team: "Client",
    assignedPersonId: "client-contact",
    coordinatorId: "james-parker",
    dueDate: "2026-09-14",
    status: "overdue",
    waitingOn: "Client",
    priority: "high",
    impactIfLate: "Execution Readiness blocked.",
    nextStep: "Follow up once revised proposal is submitted.",
  },
  {
    id: "act-5",
    title: "Complete commercial impact review",
    linkedItem: "CR-003 · Additional Treatment Scope",
    linkedHref: "/changes/cr-003",
    team: "Commercial",
    assignedPersonId: "michael-grant",
    coordinatorId: "james-parker",
    dueDate: "2026-09-12",
    status: "complete",
    waitingOn: "—",
    priority: "medium",
    impactIfLate: "Combined impact cannot reach PM decision.",
    nextStep: "Closed — cost exposure confirmed at $18,500.",
  },
  {
    id: "act-6",
    title: "Issue revised purchase order",
    linkedItem: "Procurement Readiness",
    linkedHref: "/readiness",
    team: "Procurement / Logistics",
    assignedPersonId: "sara-malik",
    coordinatorId: "james-parker",
    dueDate: "2026-09-15",
    status: "waiting",
    waitingOn: "Supplier confirmation",
    priority: "medium",
    impactIfLate: "Procurement readiness remains at risk.",
    nextStep: "Issue PO once supplier confirms revised lead time.",
  },
]

// ---------- Documents ----------
export const DOCUMENTS: DocumentRecord[] = [
  { id: "doc-client-approval", name: "Client technical approval record", type: "Client Approval", addedBy: "James Parker", date: "2026-09-12", stage: "Client Technical Review", status: "pending-review", summary: "External client technical approval is pending the revised proposal. Mock reference only." },
  { id: "doc-pilot", name: "Pilot and field validation record", type: "Pilot Test Result", addedBy: "Carlos Diaz", date: "2026-09-12", stage: "Pilot / Field Validation", status: "draft", summary: "Placeholder for specialist-recorded pilot and field validation outcomes. No technical result is inferred." },
  { id: "doc-field", name: "Field execution report", type: "Field Report", addedBy: "John Miller", date: "2026-09-12", stage: "Field Execution", status: "draft", summary: "Field report placeholder for manpower, equipment, execution progress, and operational exceptions." },
  { id: "doc-completion", name: "Technical completion report", type: "Technical Completion Report", addedBy: "Dr. Omar Rahman", date: "2026-09-12", stage: "Technical Completion", status: "draft", summary: "Technical completion report is pending specialist closeout and field verification." },
  { id: "doc-validation", name: "Client validation and sign-off record", type: "Client Validation", addedBy: "James Parker", date: "2026-09-12", stage: "Client Validation", status: "draft", summary: "External dependency. Client sign-off has not yet been received." },
  {
    id: "doc-1",
    name: "Client Technical Requirement — Produced Water Treatment",
    type: "Client Technical Requirement",
    addedBy: "James Parker",
    date: "2026-09-01",
    stage: "Contract Award",
    status: "final",
    summary:
      "Defines the scope of the produced water treatment optimization program, target facility, and client technical objectives for the North Field Processing Facility.",
  },
  {
    id: "doc-2",
    name: "Sample Analysis Report — Primary Train",
    type: "Sample Analysis",
    addedBy: "Dr. Omar Rahman",
    date: "2026-09-08",
    stage: "Lab Characterization",
    status: "final",
    summary: "Full water chemistry characterization for the primary separator train produced water stream.",
  },
  {
    id: "doc-3",
    name: "Lab Test Result — Treatment Screening",
    type: "Lab Test Result",
    addedBy: "Priya Nair",
    date: "2026-09-10",
    stage: "Treatment Test",
    status: "final",
    summary: "Bench-scale treatment screening results identifying shortlisted chemistries and dosing ranges.",
  },
  {
    id: "doc-4",
    name: "Technical Evaluation Summary",
    type: "Technical Evaluation",
    addedBy: "Dr. Omar Rahman",
    date: "2026-09-11",
    stage: "Technical Evaluation",
    status: "final",
    summary: "Evaluation of shortlisted treatment chemistries against facility constraints and recommended program.",
  },
  {
    id: "doc-5",
    name: "Technical Proposal — Rev 1",
    type: "Technical Proposal",
    addedBy: "Dr. Omar Rahman",
    date: "2026-09-11",
    stage: "Technical Proposal",
    relatedId: "cr-003",
    relatedLabel: "CR-003",
    status: "draft",
    summary: "Initial technical proposal covering the primary separator train. Revision pending CR-003 secondary train scope.",
  },
  {
    id: "doc-6",
    name: "CR-003 Supporting Document — Secondary Train Inspection",
    type: "Change Supporting Document",
    addedBy: "Robert Hayes",
    date: "2026-09-11",
    stage: "Changes",
    relatedId: "cr-003",
    relatedLabel: "CR-003",
    status: "final",
    summary: "Client-provided inspection notes describing scaling observations on the secondary separator train.",
  },
]

// ---------- Activity ----------
export const ACTIVITY: ActivityEntry[] = [
  {
    id: "act-log-1",
    timestamp: "2026-09-11 09:30",
    team: "Client",
    person: "Robert Hayes",
    event: "Client requested additional treatment scope covering the secondary separator train.",
    category: "client",
    relatedObject: { label: "CR-003", href: "/changes/cr-003" },
  },
  {
    id: "act-log-2",
    timestamp: "2026-09-11 11:10",
    team: "Technical / Lab",
    person: "Dr. Omar Rahman",
    event: "Technical impact assessment started for CR-003.",
    category: "technical",
    relatedObject: { label: "CR-003", href: "/changes/cr-003" },
  },
  {
    id: "act-log-3",
    timestamp: "2026-09-11 14:45",
    team: "Procurement / Logistics",
    person: "Sara Malik",
    event: "Procurement confirmed additional chemical requirement with a 2-day lead-time extension.",
    category: "procurement",
    relatedObject: { label: "CR-003", href: "/changes/cr-003" },
  },
  {
    id: "act-log-4",
    timestamp: "2026-09-12 09:15",
    team: "Operations",
    person: "John Miller",
    event: "Operations recorded a +3 day execution impact for CR-003.",
    category: "operations",
    relatedObject: { label: "CR-003", href: "/changes/cr-003" },
  },
  {
    id: "act-log-5",
    timestamp: "2026-09-12 13:40",
    team: "Commercial",
    person: "Michael Grant",
    event: "Commercial completed CR-003 cost review at $18,500 additional exposure.",
    category: "commercial",
    relatedObject: { label: "CR-003", href: "/changes/cr-003" },
  },
  {
    id: "act-log-6",
    timestamp: "2026-09-12 15:05",
    team: "Project Management",
    person: "James Parker",
    event: "Reviewed combined impact for CR-003 — awaiting decision.",
    category: "pm-decision",
    relatedObject: { label: "CR-003", href: "/changes/cr-003" },
  },
]
